<?php
/**
 * Uses the current URI to determine what page is currently being displayed, and updates the page title appropriately.
 *
 */
function echoPageTitle() {
    $url = strtok($_SERVER["REQUEST_URI"], '?');
    switch (basename($url, ".php")) {
        case "index":
            echo "Home";
            break;
        case "slatecrate":
            echo "Home";
            break;
        case "addclass":
            echo "New Class";
            break;
        case "editclass":
            echo "Edit Class";
            break;
        case "addlink":
            echo "New Link";
            break;
        case "editlink":
            echo "Edit Link";
            break;
        default:
            echo ucfirst(basename($url, ".php"));
            break;
    }
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" type="image/png"
          href="http://thomasbreads.com/files/images/product/main/Thomas_product_top_PLAIN_BAGEL_THIN_OVERHEAD_3C.png">

    <!-- Page title generated by PHP -->
    <title><?php echoPageTitle(); ?> | SlateCrate</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">

    <!-- Selectize CSS -->
    <link href="assets/css/selectize.css" rel="stylesheet">
    <link href="assets/css/selectize.bootstrap3.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
